add_rules("mode.debug", "mode.release")
set_toolchains("clang")
target("foo")
    set_kind("static")
    add_files("src/lib/foo/*.cpp")
    add_includedirs("src/inc/foo", {public = true})
target("package_test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("foo")
